In [1]:
import numpy as np

In [2]:
ar_1d=np.array([1,2,3,4])
print(ar_1d)

[1 2 3 4]


In [3]:
type(ar_1d)

numpy.ndarray

In [4]:
ar_1d.ndim

1

In [5]:
ar_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(ar_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
ar_2d.ndim

2

In [7]:
ar_1d.size

4

In [8]:
ar_2d.size

8

In [9]:
ar_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

ar_1d


In [10]:
ar_1d

array([1, 2, 3, 4])