# numpy

In [1]:
import numpy as np

In [25]:
# np.arange(start,end,step)
ar = np.arange(12)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
even_ar = np.arange(0,10,2)
print(even_ar)

[0 2 4 6 8]


# linspace

In [27]:
arr = np.linspace(1,10,3,dtype=int)
print(arr)

[ 1  5 10]


# reshape

In [29]:
ar_2d=ar.reshape(4,3)
print(ar_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
ar_3d = ar.reshape(2,3,2)
print(ar_3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [36]:
convert_ar = np.arange(12,24,2).reshape(3,2)
print(convert_ar)

[[12 14]
 [16 18]
 [20 22]]


# ravel

In [37]:
convert_ar.ravel()

array([12, 14, 16, 18, 20, 22])

# flatten

In [38]:
convert_ar.flatten()

array([12, 14, 16, 18, 20, 22])

# transpose

In [40]:
ar_2d.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [43]:
print(ar_2d.T)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
