# python numpy array conctination and split

In [14]:
import numpy as np

In [15]:
arr1 = np.arange(1,17).reshape(4,4)

In [16]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
arr2 = np.arange(17,33).reshape(4,4)

In [18]:
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [19]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

# concatenate

In [20]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [21]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [22]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [23]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [27]:
harr=np.hstack((arr1,arr2,arr1))

# split

In [37]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [38]:
np.split(harr,2,axis=1)

[array([[ 1,  2,  3,  4, 17, 18],
        [ 5,  6,  7,  8, 21, 22],
        [ 9, 10, 11, 12, 25, 26],
        [13, 14, 15, 16, 29, 30]]),
 array([[19, 20,  1,  2,  3,  4],
        [23, 24,  5,  6,  7,  8],
        [27, 28,  9, 10, 11, 12],
        [31, 32, 13, 14, 15, 16]])]

In [39]:
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [40]:
ar_1d = np.array([1,2,3,4,5])

In [42]:
np.split(ar_1d,[1,3])

[array([1]), array([2, 3]), array([4, 5])]