# Mathametical operation on numpy

In [1]:
import numpy as np


In [4]:
ar = np.arange(9)
print(ar_3d)

[0 1 2 3 4 5 6 7 8]


In [7]:
ar_3d=np.reshape(ar,(3,3))
print(ar_3d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(1,10).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
ar1 + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
ad_arr = np.add(ar1,ar2)
print(ad_arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
ar1-ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
sub_ar = np.subtract(ar1,ar2)
print(sub_ar)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
ar1 / ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
multi_ar = np.multiply(ar1,ar2)

In [17]:
print(multi_ar)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [18]:
ar1 @ ar2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
m_a = ar1.dot(ar2)
print(m_a)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [21]:
m_a.min()

30

In [22]:
m_a.max()

150

In [23]:
m_a.argmax()

8

In [24]:
m_a.argmin()

0

In [28]:
m_a.max(axis=1)

array([ 42,  96, 150])

In [29]:
m_a.max(axis=0)

array([102, 126, 150])

In [30]:
ar1.min(axis=0)

array([1, 2, 3])

In [31]:
ar1.min(axis=1)

array([1, 4, 7])

In [34]:
m_a.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [36]:
np.sum(m_a)

729

In [39]:
m_a = ar1.dot(ar2)
print(m_a)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [43]:
np.sum(m_a,axis=1)

array([108, 243, 378])

In [44]:
np.mean(m_a)

81.0

In [45]:
np.sqrt(m_a)

array([[ 5.47722558,  6.        ,  6.4807407 ],
       [ 8.1240384 ,  9.        ,  9.79795897],
       [10.09950494, 11.22497216, 12.24744871]])

In [46]:
np.std(ar1)

2.581988897471611

In [47]:
np.exp(m_a)

array([[1.06864746e+13, 4.31123155e+15, 1.73927494e+18],
       [4.60718663e+28, 1.50609731e+35, 4.92345829e+41],
       [1.98626484e+44, 5.26144118e+54, 1.39370958e+65]])

In [48]:
np.log(m_a)

array([[3.40119738, 3.58351894, 3.73766962],
       [4.18965474, 4.39444915, 4.56434819],
       [4.62497281, 4.83628191, 5.01063529]])

In [49]:
np.log10(m_a)

array([[1.47712125, 1.5563025 , 1.62324929],
       [1.81954394, 1.90848502, 1.98227123],
       [2.00860017, 2.10037055, 2.17609126]])

In [50]:
log_arr=np.log10(m_a)
print(log_arr)

[[1.47712125 1.5563025  1.62324929]
 [1.81954394 1.90848502 1.98227123]
 [2.00860017 2.10037055 2.17609126]]
