In [1]:
import numpy as np

In [2]:
np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
mx_1s=np.ones(2)
print(mx_1s)

[1. 1.]


In [4]:
mx_1s.dtype

dtype('float64')

In [5]:
mx_2 = np.ones((2,5))
print(mx_2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
zero_mx=np.zeros((4,5),dtype=bool)
print(zero_mx)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [17]:
zero_mx=np.zeros((4,5),order='f')
print(zero_mx)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
zero_mx=np.zeros((4,5),dtype=int)
print(zero_mx)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
mx_empty = np.empty((4,5),dtype=int,order='c')
print(mx_empty)

[[         0 1072693248          0 1072693248          0]
 [1072693248          0 1072693248          0 1072693248]
 [         0 1072693248          0 1072693248          0]
 [1072693248          0 1072693248          0 1072693248]]
