# Random Sampling with numpy

In [1]:
import numpy as np

In [5]:
np.random.random(1)

array([0.55599967])

In [7]:
np.random.random((2,6))

array([[0.84024821, 0.43621564, 0.19905265, 0.74488161, 0.7972842 ,
        0.85147362],
       [0.45065603, 0.84918076, 0.00589361, 0.10059928, 0.26009438,
        0.1355461 ]])

In [18]:
np.random.randint(5)

2

In [27]:
arr = np.random.randint(1,3,(4,4,4))
print(arr)

[[[2 2 2 1]
  [2 2 1 2]
  [1 1 2 1]
  [2 1 1 2]]

 [[1 1 1 1]
  [2 2 2 2]
  [2 1 2 2]
  [1 1 2 2]]

 [[1 1 2 1]
  [2 1 2 2]
  [1 1 2 2]
  [1 2 1 1]]

 [[2 1 2 1]
  [2 1 1 2]
  [1 1 1 2]
  [1 2 2 2]]]
