# NumPy Array Iterating

In [1]:
import numpy as np

In [5]:
arr = np.arange(1,10).reshape(3,3)

In [12]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
for i in range(len(arr)):
    print(arr[i])

[1 2 3]
[4 5 6]
[7 8 9]
